import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* remove default body margin and make body full width */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-0 w-full`}
      >
        {/* make top-level wrapper full width — allow page components to handle internal padding */}
       <div className="w-full min-h-screen overflow-x-hidden">
       <Header />
      {children}
       </div>
      </body>
    </html>
  );
}

